import Head from "next/head";
import { BiUserPlus } from "react-icons/bi";
import Form from "@/components/form";
import Link from "next/link";
import { useState } from "react";
import Table from "@/components/table";

export default function Home() {
  const [visible, setVisible] = useState(false);
  const handler = () => setVisible(!visible);

  return (
    <section>
      <Head>
        <title>CRUD Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-10">
        <h1>
          <Link href="/test">test</Link>
        </h1>
        <h1 className="text-xl md:text-5xl text-center font-bold py-10">
          Employee Management
        </h1>
        <div className="container mx-auto justify-between py-5 border-b">
          <div className="left flex gap-3">
            <button
              onClick={handler}
              className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-800"
            >
              Add Employee
              <span className="px-1">
                <BiUserPlus size={23} />
              </span>
            </button>
          </div>
        </div>
        {visible ? <Form></Form> : <></>}
        <div className="container mx-auto">
          <Table></Table>
        </div>
      </main>
    </section>
  );
}
